name: CI
on:
  push:
    branches: [ "main" ]
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v4
      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.1228247.xyz
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/astro/**
